Remove ipywidgets
conda-forge/openff-toolkit-feedstock pull request #57
Opened 2023-07-01 11:56 UTC by hadim

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-07-01 11:57 UTC, hadim commented
nglview >=3.0.4 supports latest ipyqidgets in both notebook and jlab: https://github.com/nglviewer/nglview/releases

2023-07-01 11:57 UTC, hadim commented
@conda-forge-admin, please rerender

2023-07-01 12:17 UTC, hadim commented
@conda-forge/openff-toolkit ready for review!

2023-07-01 14:26 UTC, mattwthompson requested changes

2023-07-01 14:26 UTC, mattwthompson commented on recipe/meta.yaml
> +  number: 10
```suggestion
  number: 1
```

2023-07-01 14:27 UTC, mattwthompson commented
@Yoshanuikabundi found an issue with some combination of NGLview, JupyterLab, and Colab, but I think that's a compatibility issue with the latter two that we're not dealing with here, so this change should be fine, right Josh?

2023-07-03 08:27 UTC, Yoshanuikabundi commented
I thought NGLView didn't work with JupyterLab 4.x, but it looks like it does work with lab 4 locally if I specify IPyWidgets 8.x. I thought I had tested it with an environment that was just Lab and NGLview but I guess I didn't. Colab doesn't seem to work in either case but now that I know this I'm making progress on that.

In other words this change may actually fix that issue!

2023-07-03 14:00 UTC, mattwthompson commented
Let's roll with this for now, then. While we're unsure of limitations we should be permissive

2023-07-03 14:00 UTC, mattwthompson approved these changes

2023-07-03 14:00 UTC, merged

2023-07-03 15:14 UTC, j-wags commented
Perfect - Thanks everyone!